### ISSUE TITLE
Could not find and/or execute program specified by service

### ISSUE THREAD

**Issue by phillprice** [codechimp-org/ha-menu#51] opened 2020-08-17 14:06 UTC
I see this in `/var/log/system.log` every 10 seconds (the program functions as normal)

Should I be concerned?
```
Aug 17 15:05:49 [machine] com.apple.xpc.launchd[1] (org.codechimp.HA-Menu-Launcher[68705]): Could not find and/or execute program specified by service: 155: Refusing to execute/trust quarantined program/file: org.codechimp.HA-Menu-Launcher
Aug 17 15:05:49 [machine] com.apple.xpc.launchd[1] (org.codechimp.HA-Menu-Launcher[68705]): Service exited with abnormal code: 78
Aug 17 15:05:49 [machine] com.apple.xpc.launchd[1] (org.codechimp.HA-Menu-Launcher): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
```

**Comment by andrew-codechimp** [comment] 2020-08-17 14:21
HA-Menu-Launcher is part of HA-Menu and is used to start it on boot so it's a known part of HA-Menu.
The app is sandboxed and notarized by Apple so can't do any harm outside of its own container. 

Why you're getting the logs I don't know though, just checked mine and they're not there.
How did you install it, from the ZIP or via Homebrew?

**Comment by phillprice** [comment] 2020-08-17 16:07
I installed from zip. It’s Mojave if that helps. Not that it’s affecting performance.

**Comment by andrew-codechimp** [comment] 2020-08-17 16:16
Thanks for the details, Zip is the way I have tested most so rules that out.
I only have Catalina to test against so maybe it's something odd with Mojave, I'll look into it as never good to have unusual log entries but the Open at Startup code was a new area to me so I'm probably missing some nuance I need to handle.

**Comment by andrew-codechimp** [comment] 2022-03-09 13:31
Closing as still unable to reproduce and no further reports.

**Closed by andrew-codechimp** 2022-03-09 13:31 UTC
Labels: bug
